// Mock product catalog — 40 products across 4 categories
// Images: Unsplash CDN with onerror fallback handled in renderProductCard
const GU_PRODUCTS = [

  // ── RUNNING (10) ──────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Velocity Pro Running Shoes",
    category: "Running",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight, responsive running shoes engineered for speed and long-distance comfort. Breathable mesh upper with energy-return foam midsole.",
    featured: true,
  },
  {
    id: 2,
    name: "Sprint Elite Track Spikes",
    category: "Running",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=600&q=80",
    description: "Competition-ready track spikes with a rigid carbon-fiber plate for maximum propulsion off the blocks.",
    featured: false,
  },
  {
    id: 3,
    name: "Endurance Trail Runner",
    category: "Running",
    price: 114.99,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
    description: "Rock-plate protected trail runners built for rugged terrain. Water-resistant upper keeps feet dry in all conditions.",
    featured: true,
  },
  {
    id: 4,
    name: "AeroGlide Running Vest",
    category: "Running",
    price: 54.99,
    image: "https://images.unsplash.com/photo-1556906781-9a412961a28f?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-breathable running vest with moisture-wicking fabric, reflective strips, and two zip pockets.",
    featured: false,
  },
  {
    id: 5,
    name: "ProForm Compression Tights",
    category: "Running",
    price: 64.99,
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=600&q=80",
    description: "Graduated compression tights with flatlock seams for chafe-free long runs. UPF 50+ fabric.",
    featured: false,
  },
  {
    id: 6,
    name: "Carbon Racer Flat",
    category: "Running",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80",
    description: "Race-day flat with a full-length carbon plate and super-foam stack. Built for sub-3 marathon performance.",
    featured: true,
  },
  {
    id: 7,
    name: "HydroTrail Running Pack",
    category: "Running",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80",
    description: "10L hydration running vest with 2L bladder, bounce-free fit, and emergency whistle. Ideal for ultras.",
    featured: false,
  },
  {
    id: 8,
    name: "NightRun Reflective Jacket",
    category: "Running",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=600&q=80",
    description: "360° reflective running jacket with laser-cut ventilation, packable design, and thumb loops.",
    featured: false,
  },
  {
    id: 9,
    name: "AeroCool Running Cap",
    category: "Running",
    price: 28.99,
    image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=600&q=80",
    description: "Ultralight mesh running cap with a sweat-wicking band and pre-curved brim for sun protection.",
    featured: false,
  },
  {
    id: 10,
    name: "SpeedSock No-Show 3-Pack",
    category: "Running",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&q=80",
    description: "Cushioned no-show socks with a seamless toe box and silicone heel grip. Moisture-wicking nylon blend.",
    featured: false,
  },

  // ── TRAINING (10) ─────────────────────────────────────────────────────────
  {
    id: 11,
    name: "PowerLift Training Shoes",
    category: "Training",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
    description: "Zero-drop, flat-soled training shoes with a wide toe box and stability plate for heavy lifting and HIIT.",
    featured: true,
  },
  {
    id: 12,
    name: "FlexCore Training Shorts",
    category: "Training",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
    description: "4-way stretch training shorts with a built-in liner, side zip pockets, and a secure elastic waistband.",
    featured: false,
  },
  {
    id: 13,
    name: "IronGrip Lifting Gloves",
    category: "Training",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80",
    description: "Full-palm padded lifting gloves with adjustable wrist straps. Improves grip on heavy pulls and presses.",
    featured: false,
  },
  {
    id: 14,
    name: "Agility Speed Rope",
    category: "Training",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=600&q=80",
    description: "Precision-weighted speed rope with sealed ball-bearing handles. Adjustable cable fits most heights.",
    featured: false,
  },
  {
    id: 15,
    name: "PowerBand Resistance Set",
    category: "Training",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1517963628246-ef38ef693dd6?auto=format&fit=crop&w=600&q=80",
    description: "5-band resistance set (10–50 lb) with carry bag and door anchor. Perfect for home and travel training.",
    featured: false,
  },
  {
    id: 16,
    name: "ProLift Weightlifting Belt",
    category: "Training",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1581009137042-c552e485697a?auto=format&fit=crop&w=600&q=80",
    description: "4-inch genuine leather weightlifting belt with double-prong buckle. Provides lumbar support for maximal lifts.",
    featured: true,
  },
  {
    id: 17,
    name: "StrongGrip Pull-Up Bar",
    category: "Training",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80",
    description: "Doorframe pull-up bar with multi-grip positions. No screws, holds up to 300 lb. Foam-padded grips.",
    featured: false,
  },
  {
    id: 18,
    name: "CoreRoll Ab Wheel",
    category: "Training",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80",
    description: "Dual-wheel ab roller with a non-slip kneel pad and ergonomic foam handles for controlled core activation.",
    featured: false,
  },
  {
    id: 19,
    name: "PerformanceX Training Shirt",
    category: "Training",
    price: 38.99,
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80",
    description: "Slim-fit training shirt with anti-odor fabric, laser-perforated ventilation panels, and flatlock seams.",
    featured: false,
  },
  {
    id: 20,
    name: "Gym Pro Duffel 30L",
    category: "Training",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1547482887-96e1c43b9bd4?auto=format&fit=crop&w=600&q=80",
    description: "30L gym duffel with a ventilated shoe compartment, water-resistant base, and removable shoulder strap.",
    featured: false,
  },

  // ── FOOTBALL (10) ─────────────────────────────────────────────────────────
  {
    id: 21,
    name: "Striker Football Cleats",
    category: "Football",
    price: 124.99,
    image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80",
    description: "Firm-ground cleats with a conical-stud outsole for explosive multidirectional speed. Padded ankle collar.",
    featured: true,
  },
  {
    id: 22,
    name: "TacklePro Shoulder Pads",
    category: "Football",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?auto=format&fit=crop&w=600&q=80",
    description: "Low-profile, high-impact shoulder pads with integrated rib protection and ventilated back plate.",
    featured: true,
  },
  {
    id: 23,
    name: "GridironGrip Football",
    category: "Football",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1551958219-acbc595d5c5f?auto=format&fit=crop&w=600&q=80",
    description: "Official size composite leather football with a raised lace pattern and all-weather grip coating.",
    featured: false,
  },
  {
    id: 24,
    name: "Compression Arm Sleeves",
    category: "Football",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
    description: "UV-protective compression sleeves with 20–30 mmHg graduated compression for improved circulation on the field.",
    featured: false,
  },
  {
    id: 25,
    name: "Receiver Pro Gloves",
    category: "Football",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1529932512988-81c5cde1bc06?auto=format&fit=crop&w=600&q=80",
    description: "Tacky-palm receiver gloves with backhand ventilation and wrist strap. Approved for game use.",
    featured: false,
  },
  {
    id: 26,
    name: "GameDay Practice Jersey",
    category: "Football",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=600&q=80",
    description: "Moisture-wicking mesh practice jersey with reinforced side panels and number-ready screen printing.",
    featured: false,
  },
  {
    id: 27,
    name: "SpeedEdge Turf Cleats",
    category: "Football",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6?auto=format&fit=crop&w=600&q=80",
    description: "Multi-stud turf cleats with a knit upper and rubber outsole optimized for artificial surface traction.",
    featured: false,
  },
  {
    id: 28,
    name: "VisionPro Football Helmet",
    category: "Football",
    price: 189.99,
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=600&q=80",
    description: "NOCSAE-certified helmet with multi-layer foam liner, tool-less facemask, and integrated jaw pad system.",
    featured: true,
  },
  {
    id: 29,
    name: "Elite Kicking Tee Set",
    category: "Football",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&w=600&q=80",
    description: "3-pack of kicking tees in varying heights (1\", 2\", 3\") for kickoffs and field goal practice.",
    featured: false,
  },
  {
    id: 30,
    name: "Agility Cone Set 20-Pack",
    category: "Football",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1519311965067-36d3e5f33d39?auto=format&fit=crop&w=600&q=80",
    description: "Durable 9-inch sport cones for agility drills, 4-corner routes, and speed training. UV-resistant plastic.",
    featured: false,
  },

  // ── ACCESSORIES (10) ──────────────────────────────────────────────────────
  {
    id: 31,
    name: "HydroRush Insulated Bottle",
    category: "Accessories",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "32oz triple-walled stainless steel bottle, ice-cold 24h or hot 12h. Leak-proof lid with carry loop.",
    featured: false,
  },
  {
    id: 32,
    name: "VeloMesh Sport Backpack",
    category: "Accessories",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "30L ventilated sport backpack with dedicated shoe tunnel, wet pocket, and padded laptop sleeve.",
    featured: true,
  },
  {
    id: 33,
    name: "RecoveryFlex Foam Roller",
    category: "Accessories",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=600&q=80",
    description: "High-density EVA foam roller with textured surface for myofascial release and post-workout recovery.",
    featured: false,
  },
  {
    id: 34,
    name: "EliteTrack Socks 3-Pack",
    category: "Accessories",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&q=80",
    description: "Arch-support compression socks with moisture-wicking nylon. Tab-back prevents heel slippage.",
    featured: false,
  },
  {
    id: 35,
    name: "PowerPulse Massage Gun",
    category: "Accessories",
    price: 119.99,
    image: "https://images.unsplash.com/photo-1616279969771-0f24e7e8e9de?auto=format&fit=crop&w=600&q=80",
    description: "Percussive massage gun with 6 heads, 5 speeds, and 3200 rpm. Whisper-quiet motor, 6-hour battery.",
    featured: true,
  },
  {
    id: 36,
    name: "Sport Chalk Block 3-Pack",
    category: "Accessories",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?auto=format&fit=crop&w=600&q=80",
    description: "Pure magnesium carbonate chalk blocks for improved grip on bars, rings, and kettlebells.",
    featured: false,
  },
  {
    id: 37,
    name: "UltraDry Sport Towel",
    category: "Accessories",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?auto=format&fit=crop&w=600&q=80",
    description: "Quick-dry microfiber gym towel, 24\" × 48\". Absorbs 4× its weight, packs to the size of a water bottle.",
    featured: false,
  },
  {
    id: 38,
    name: "ProMix Protein Shaker",
    category: "Accessories",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=600&q=80",
    description: "28oz BPA-free shaker with a stainless mixing ball, measurement markings, and leak-proof flip cap.",
    featured: false,
  },
  {
    id: 39,
    name: "Resistance Loop Bands 5-Pack",
    category: "Accessories",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1598632640487-6ea4a4e8b963?auto=format&fit=crop&w=600&q=80",
    description: "Latex-free fabric resistance loops in 5 progressive resistances. Ideal for glute activation and mobility work.",
    featured: false,
  },
  {
    id: 40,
    name: "VivoFit Sport Watch",
    category: "Accessories",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80",
    description: "GPS sport watch with heart-rate monitor, pace tracking, interval timer, and 7-day battery life.",
    featured: true,
  },
];
