// Mock product catalog — 16 products across 4 categories
const GU_PRODUCTS = [
  {
    id: 1,
    name: "Velocity Pro Running Shoes",
    category: "Running",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    description: "Lightweight, responsive running shoes engineered for speed and long-distance comfort. Features a breathable mesh upper and energy-return foam midsole.",
    featured: true,
  },
  {
    id: 2,
    name: "Sprint Elite Track Spikes",
    category: "Running",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80",
    description: "Competition-ready track spikes with a rigid carbon-fiber plate for maximum propulsion off the blocks. Fits true to size.",
    featured: false,
  },
  {
    id: 3,
    name: "Endurance Trail Runner",
    category: "Running",
    price: 114.99,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
    description: "Rock-plate protected trail runners built for rugged terrain. Water-resistant upper keeps feet dry in all conditions.",
    featured: true,
  },
  {
    id: 4,
    name: "AeroGlide Running Vest",
    category: "Running",
    price: 54.99,
    image: "https://images.unsplash.com/photo-1556906781-9a412961a28f?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-breathable running vest with moisture-wicking fabric, reflective strips, and two zip pockets for essential gear.",
    featured: false,
  },
  {
    id: 5,
    name: "PowerLift Training Shoes",
    category: "Training",
    price: 99.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=600&q=80",
    description: "Zero-drop, flat-soled training shoes with a wide toe box and enhanced stability plate — ideal for squats, deadlifts, and HIIT circuits.",
    featured: true,
  },
  {
    id: 6,
    name: "FlexCore Training Shorts",
    category: "Training",
    price: 44.99,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
    description: "4-way stretch training shorts with a built-in moisture-wicking liner, side zip pockets, and a secure elastic waistband.",
    featured: false,
  },
  {
    id: 7,
    name: "IronGrip Lifting Gloves",
    category: "Training",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80",
    description: "Full-palm padded lifting gloves with adjustable wrist straps. Improves grip confidence on heavy pulls and presses.",
    featured: false,
  },
  {
    id: 8,
    name: "Agility Speed Rope",
    category: "Training",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1598971457999-ca6a8349b9a0?auto=format&fit=crop&w=600&q=80",
    description: "Precision-weighted speed rope with sealed ball-bearing handles. Pre-cut cable fits most heights and is fully adjustable.",
    featured: false,
  },
  {
    id: 9,
    name: "Striker Football Cleats",
    category: "Football",
    price: 124.99,
    image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&w=600&q=80",
    description: "Firm-ground football cleats with a conical-stud outsole for explosive multidirectional speed. Synthetic leather upper with padded ankle collar.",
    featured: true,
  },
  {
    id: 10,
    name: "TacklePro Shoulder Pads",
    category: "Football",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?auto=format&fit=crop&w=600&q=80",
    description: "Low-profile, high-impact shoulder pads with integrated rib protection and a ventilated back plate. Engineered for skill positions.",
    featured: true,
  },
  {
    id: 11,
    name: "GridironGrip Football",
    category: "Football",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1551958219-acbc595d5c5f?auto=format&fit=crop&w=600&q=80",
    description: "Official size composite leather football with a raised lace pattern and all-weather grip coating. Great for training and pickup games.",
    featured: false,
  },
  {
    id: 12,
    name: "Compression Arm Sleeves",
    category: "Football",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1509833903111-9cb142f644e4?auto=format&fit=crop&w=600&q=80",
    description: "UV-protective compression sleeves with graduated 20-30 mmHg compression for improved circulation and sun coverage on the field.",
    featured: false,
  },
  {
    id: 13,
    name: "HydroRush Insulated Bottle",
    category: "Accessories",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
    description: "32oz triple-walled stainless steel bottle keeps drinks ice-cold for 24h or hot for 12h. Leak-proof lid with carry loop.",
    featured: false,
  },
  {
    id: 14,
    name: "VeloMesh Sport Backpack",
    category: "Accessories",
    price: 69.99,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80",
    description: "30L ventilated sport backpack with a dedicated shoe tunnel, wet pocket, and padded laptop sleeve. Built for the gym-to-office commute.",
    featured: true,
  },
  {
    id: 15,
    name: "RecoveryFlex Foam Roller",
    category: "Accessories",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=600&q=80",
    description: "High-density EVA foam roller with a textured surface for targeted myofascial release and post-workout recovery sessions.",
    featured: false,
  },
  {
    id: 16,
    name: "EliteTrack Socks (3-Pack)",
    category: "Accessories",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=600&q=80",
    description: "Arch-support compression socks with moisture-wicking nylon blend. Tab-back design prevents heel slippage during training.",
    featured: false,
  },
];
